import { PortfolioItem, Review, FaqItem, ServiceType, ServiceData } from './types';
import { Globe, Star, Instagram } from 'lucide-react';

const DEFAULT_AVATAR = 'https://ui-avatars.com/api/?background=0D8ABC&color=fff&name=';

export const content = {
  el: {
    nav: {
      services: 'Υπηρεσίες',
      portfolio: 'Πορτφόλιο',
      reviews: 'Αξιολογήσεις',
      faq: 'FAQ',
      contact: 'Επικοινωνία',
      lang: 'EN'
    },
    hero: {
      badge: 'ADVON MEDIA',
      titlePrefix: 'Μετατρέπουμε',
      titleHighlight1: 'Επισκέπτες',
      titleConnector: 'σε',
      titleHighlight2: 'Πελάτες',
      subtitle: 'Οι πιο αποτελεσματικές λύσεις marketing για τοπικές επιχειρήσεις και ελεύθερους επαγγελματίες. Ανεβείτε στην κορυφή των αποτελεσμάτων χωρίς ρίσκο.',
      ctaPrimary: 'ΥΠΗΡΕΣΙΕΣ',
      ctaSecondary: 'ΠΟΡΤΦΟΛΙΟ'
    },
    stats: [
      { num: "2+", label: "ΧΡΟΝΙΑ ΕΜΠΕΙΡΙΑΣ" },
      { num: "50+", label: "ΙΚΑΝΟΠΟΙΗΜΕΝΟΙ ΠΕΛΑΤΕΣ" },
      { num: "100%", label: "ΕΠΙΤΥΧΙΑ" },
      { num: "30+", label: "5-STAR REVIEWS" }
    ],
    sectionTitles: {
      services: 'Υπηρεσίες',
      servicesMain: 'Λύσεις που Αποδίδουν',
      servicesSub: 'Ολοκληρωμένες λύσεις για την ψηφιακή σας παρουσία.',
      noCommitment: 'Χωρίς δεσμεύσεις - Cancel Anytime',
      portfolio: 'Πορτφόλιο',
      portfolioMain: 'Δείτε μερικές από τις Δουλειές μας',
      portfolioSub: 'Δείγματα δουλειάς από ευχαριστημένους πελάτες.',
      viewSite: 'Προβολή Ιστοσελίδας',
      reviews: 'Αξιολογήσεις',
      reviewsMain: 'Τι λένε οι πελάτες μας',
      viewAllReviews: 'Δείτε Όλες τις Αξιολογήσεις',
      faq: 'Συχνές Ερωτήσεις',
      contact: 'Επικοινωνία',
      contactMain: 'Ας Συνεργαστούμε',
      contactSub: 'Στείλτε μας email με το τηλέφωνό σας για να συζητήσουμε τι ακριβώς χρειάζεστε.'
    },
    portfolioItems: [
      { image: 'https://github.com/agelmet/Image-hosting-/blob/main/11.jpg?raw=true', url: 'https://talamagka-psychologos.gr/home', name: 'Ταλαμάγκα Ελπίδα - Ψυχολόγος' },
      { image: 'https://github.com/agelmet/Image-hosting-/blob/main/22.jpg?raw=true', url: 'https://roza-psychologist.gr', name: 'Χαρουτιουνιάν Ρόζα - Ψυχολόγος' },
      { image: 'https://github.com/agelmet/Image-hosting-/blob/main/33.jpg?raw=true', url: 'https://zampelis-psychology.gr', name: 'Ζαμπέλης Στέφανος - Ψυχολόγος' },
      { image: 'https://github.com/agelmet/Image-hosting-/blob/main/44.jpg?raw=true', url: 'https://nakou-psychologos.gr', name: 'Νάκου Δήμητρα - Ψυχολόγος' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/6720fff573cc5fde7d814b0c.png', url: 'https://rhodesdentist.gr', name: 'Γλυνός Γεώργιος - Οδοντίατρος' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/6720fff57002eeb8d74c581c.png', url: 'https://apartmentsin-greece.gr', name: 'Αθήνα + Κρήτη - Διαμερίσματα' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/6720fff5be2f992fd50c4409.png', url: 'https://pediatrician-ioannisloukas.gr/en', name: 'Λουκάς Ιωάννης - Παιδίατρος' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/69025bdb3e45df05181238c1.jpeg', url: 'https://loulou-physiotherapy.gr', name: 'Λουλού Χρυσάνθη - Φυσικοθεραπεύτρια' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/69025bdb7e579816e94176ed.jpeg', url: 'https://sofiavassiliadou-psyxiatros.gr', name: 'Βασιλειάδου Σοφία - Ψυχίατρος' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/69025bdb5d191555856d1f45.jpeg', url: 'https://pappa-psyxologos.gr', name: 'Παππά Εμμανουέλα - Ψυχολόγος' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/69025bdb10e4602f322522a4.jpeg', url: 'https://oikonomou-psyxologos.gr', name: 'Οικονόμου Χρυσούλα - Ψυχολόγος' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/69025bdb5bfb334b18eec0a9.jpeg', url: 'https://stylianidou-psyxologos.gr', name: 'Στυλιανίδου Σοφία - Ψυχολόγος' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/69025bdbdf45434ecfb96d36.jpeg', url: 'https://tsekourakis-physiotherapy.gr', name: 'Τσεκουράκης Χρόνης - Φυσικοθεραπευτής' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/69031419ad87b047b548b858.jpeg', url: 'https://smaragdadimitra.gr', name: 'Δημητρά Σμαράγδα - Ψυχολόγος' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/690314195170a503ad1b3a49.jpeg', url: 'https://antamian-physiotherapy.gr', name: 'Ανταμιάν Ερμιόνη - Φυσικοθεραπεύτρια' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/69031419ad87b0376a48b859.jpeg', url: 'https://dorasizopoulou.gr', name: 'Σιζοπούλου Θεοδώρα - Ψυχολόγος' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/690314195170a593181b3a4a.jpeg', url: 'https://zoetherapy.gr', name: 'Ανδρεαδάκη Ζωή - Ψυχολόγος' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/69031419762d2cf9e43378e1.jpeg', url: 'https://memagiagkini-psyxologos.gr', name: 'Γιαγκίνη Μέμα - Ψυχολόγος' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/68d954cfa1d2dc78adcfe610.jpeg', url: 'https://tsialiafa-dentalcare.gr', name: 'Τσιαλιάφα Ελένη - Οδοντίατρος' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/68d954cfa1d2dc95f3cfe5fb.jpeg', url: 'https://chatzistratis-paidiatros.gr', name: 'Χατζηστρατής Στράτος - Παιδίατρος' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/68d954cf4c35d613678773f5.jpeg', url: 'https://occludent.gr', name: 'Φασούλα Μαρία - Οδοντίατρος' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/68d954cfa1d2dc0857cfe5fc.jpeg', url: 'https://papathomas-vision.gr', name: 'Θωμάς Παπαθωμάς - Οφθαλμίατρος' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/68d954cf337bbf261a42bbc3.jpeg', url: 'https://kk-dental.gr', name: 'Κωνσταντινίδης Κωνσταντίνος - Οδοντίατρος' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/68d954cf4c35d6bcaf8773f6.jpeg', url: 'https://mysmile-prosthodontics.gr', name: 'Μορδοχάι Νικήτας - Οδοντίατρος' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/6720fff5e811867d962b0b12.png', url: 'https://wonderfulspecs.gr', name: 'WonderfulSpecs - Οπτικά' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/6720fff57d6e345146f91a82.png', url: 'https://astra-paidiatros.gr', name: 'Αστρά Ελένη - Παιδίατρος' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/672106acbe2f9908390c468b.png', url: 'https://barampouti-ofthalmiatros.gr', name: 'Μπαραμπούτη Φαίη - Οφθαλμίατρος' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/684c2972bc1bea3590d2fcd5.jpeg', url: 'https://eye-orl.gr', name: 'Οφθαλμίατρος + Ωτορινολαρυγγολόγος' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/684c2972e3c40936dec8067b.jpeg', url: 'https://davou-ofthalmiatros.gr', name: 'Δάβου Σταυρούλα - Οφθαλμίατρος' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/684c29725cb3bb547ceacc82.jpeg', url: 'https://vouza-ofthalmiatros.gr', name: 'Βούζα Ασπασία - Οφθαλμίατρος' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/684c297207bcd3c2755ce584.jpeg', url: 'https://thetidasvilla.gr', name: 'Κάρπαθος - Βίλα' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/684c297207bcd3a84a5ce586.jpeg', url: 'https://panousopoulou-paidiatros.gr', name: 'Πανουσοπούλου Χριστίνα - Παιδίατρος' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/684c2972fbe6f42e908208cb.jpeg', url: 'https://giamouris-paidiatros.gr', name: 'Γιαμούρης Μανόλης - Παιδίατρος' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/684c29722809a9b32a06926f.jpeg', url: 'https://theodosis-orila.gr', name: 'Θεοδώσης Πέτρος - Ωτορινολαρυγγολόγος' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/684c297251e5e5089ade7e7e.jpeg', url: 'https://zormpa-dentist.gr', name: 'Ζορμπά Θωμαής - Οδοντίατρος' },
    ],
    reviews: [
      { image: 'https://lh3.googleusercontent.com/a-/ALV-UjXyvVDSorQzQz3Z-zsqvl68SOOgYiq4C3UBH8punVUaFZrC7wDkug=w144-h144-p-rp-mo-br100', name: 'Ελπίδα Ταλαμάγκα', rating: 5, text: 'Ειμαι ψυχολόγος και συνεργάστηκα με την Advon Media για τη δημιουργία του επαγγελματικού μου site. Τα παιδιά είναι εξαιρετικά!!! Άψογη δουλειά, 100% επαγγελματίες & πολύ συνεπείς. Πολύ ευγενικοί & διατεθειμένοι να συζητήσουν την όποια αλλαγή, ώστε το site μου να είναι ακριβώς όπως το είχα φανταστει!! Άγγελε σε ευχαριστώ!!' },
      { image: DEFAULT_AVATAR + 'Ρόζα+Χαρουτιουνιάν', name: 'Ρόζα Χαρουτιουνιάν', rating: 5, text: 'Η συνεργασία μου με την ομάδα της Advon Media και ιδιαίτερα με τον κύριο Άγγελο για τη δημιουργία του επαγγελματικού μου προφίλ ήταν εξαιρετική. Από την πρώτη στιγμή ήταν ευγενικός, προσιτός και πραγματικά πρόθυμος να ακούσει τις επιθυμίες μου. Έδειξε επαγγελματισμό, συνέπεια και ενδιαφέρον για το καλύτερο δυνατό αποτέλεσμα, δίνοντας προσοχή στη λεπτομέρεια και προτείνοντας πολύ καλές ιδέες. Τους συστήνω σε όποιον αναζητά ποιοτική δουλειά και άριστη συνεργασία. Ευχαριστώ πολύ! Ρόζα Χαρουτιουνιάν, Ψυχολόγος - Ψυχοθεραπεύτρια.' },
      { image: DEFAULT_AVATAR + 'Χρύσα+Οικονόμου', name: 'Χρύσα Οικονόμου', rating: 5, text: 'Εξαιρετική η ομάδα τους! Άψογη ολη η συνεργασία μας! Απο την πρώτη μας επικοινωνία, έγινε αντιληπτός ο επαγγελματισμός και η εμπειρία τους. Κατασκεύασαν με μεγάλη ταχύτητα, συνέπεια και αισθητική το website μου. Ήταν πάντα διαθέσιμοι να απαντήσουν στις απορίες μου, να προτείνουν λύσεις και να υλοποιήσουν άμεσα όποια τροποποίηση θέλησα να κάνω. Τους συστήνω ανεπιφύλακτα γιατι το τελικό αποτέλεσμα ξεπερασε τις προσδοκίες μου!' },
      { image: DEFAULT_AVATAR + 'Ναταλία+Γρυλωνάκη', name: 'Ναταλία Γρυλωνάκη', rating: 5, text: 'Εξαιρετικοί επαγγελματίες. Ευγενικοί και ιδιαίτερα πρόθυμοι εξαρχής να λύσουν όλες μου τις απορίες και να κάνουν όποια τροποποίηση επιθυμούσα. Συνεπείς και δημιουργικοί. Το τελικό αποτέλεμα σύγχρονο, λειτουργικό και καλαίσθητο με άφησε απόλυτα ικανοποιημένη. Τους συστήνω ανεπιφύλακτα.' },
      { image: 'https://lh3.googleusercontent.com/a-/ALV-UjXwzVoH8tFi5PJF8D8skvbm3K_MVRDQOVJDpeCoiW7ldSBbVCM=w144-h144-p-rp-mo-br100', name: 'Στυλιανίδου Σοφία', rating: 5, text: 'Εξαιρετικοί επαγγελματίες υπήρξε άμεση ανταπόκριση στη δημιουργία της ιστοσελίδας μου. Τέλος ήταν ανοιχτοί να μου εξηγήσουν την οποιαδήποτε απορία είχα και να αλλάξουν οτιδήποτε χρειάστηκε. Τους συστήνω ανεπιφύλακτα.' },
      { image: 'https://lh3.googleusercontent.com/a-/ALV-UjUIFeV7kJ81o_SxrHrpj0c_WK6-zPwV-xoJGSduKwsBrps_nN8=w144-h144-p-rp-mo-br100', name: 'Εμμανουέλα Παππά', rating: 5, text: 'Τα παιδιά ήταν εξαιρετικά επαγγελματίες, ευγενικοί και πρόθυμοι να βοηθήσουν σε κάθε στάδιο της δημιουργίας του site μου. Δούλεψαν με απίστευτη ταχύτητα, άκουσαν προσεκτικά τι ήθελα ! Το site βγήκε ακριβώς όπως το είχα φανταστεί ,απλό , σύγχρονο, λειτουργικό και αισθητικά άψογο. Τους συστήνω ανεπιφύλακτα!' },
      { image: DEFAULT_AVATAR + 'Μαρία+Φασούλα', name: 'Μαρία Φασούλα', rating: 5, text: 'Άριστοι επαγγελματίες! Πολύ αξιόπιστοι και συνεπείς στα χρονοδιαγράμματα, με εξαιρετική επικοινωνία και επαγγελματική συμπεριφορά. Η ιστοσελίδα παραδόθηκε ακριβώς όπως τη φανταζόμουνα, λειτουργική και καλαίσθητη. Τους συνιστώ ανεπιφύλακτα για όποιον αναζητά ποιοτική και υπεύθυνη δουλειά!!!' },
      { image: DEFAULT_AVATAR + 'Ελένη+Τσιαλιάφα', name: 'Ελένη Τσιαλιάφα', rating: 5, text: 'Άψογοι επαγγελματίες με συνέπεια και ταχύτητα στην εξυπηρέτηση. Λεπτομερής και προσεγμένη δουλειά. Μπράβο στην ομάδα! Τους συστήνω ανεπιφύλακτα. Τσιαλιάφα Ελένη Χειρ.Οδοντίατρος' },
      { image: DEFAULT_AVATAR + 'Σοφία+Βασιλειάδου', name: 'Σοφία Βασιλειάδου', rating: 5, text: 'Όλη η ομάδα της Advon Media λειτούργησε με φοβερό επαγγελματισμό και μεγάλη ταχύτητα. Το αποτέλεσμα ξεπέρασε τις προσδοκίες μου, τους ευχαριστώ πολύ και εννοείται ότι συστήνω την Advon Media ανεπιφύλακτα!' },
      { image: 'https://lh3.googleusercontent.com/a-/ALV-UjX1bbMbwmzkQEWSP45s29CBn4twUfVMISTrmfepCc8o3z9P8foekg=w144-h144-p-rp-mo-br100', name: 'Σμαράγδα Δημητρά', rating: 5, text: 'Εξαιρετική δουλειά, πολύ καλή επικοινωνία' },
      { image: 'https://lh3.googleusercontent.com/a-/ALV-UjVL1O97zqNUKHWBzFz9HIbvUc6__rUq_HdJELt-S-OZhixDk3fR=w144-h144-p-rp-mo-ba3-br100', name: 'Παναγιώτης Ιατρούδης', rating: 5, text: 'Πολύ καλή και επαγγελματική συνεργασία για την κατασκευή της ιστοσελίδας μου. Τους έχω ήδη συστήσει και σε άλλους! Ιατρούδης Παναγιώτης Οδοντίατρος' },
      { image: 'https://lh3.googleusercontent.com/a-/ALV-UjWaGCVmAUJX0HX3Fxdt8YIs7h8Yn9py1LkLWI2h1lIqBvhgk89t=w144-h144-p-rp-mo-ba5-br100', name: 'Γλυνός Γιώργος', rating: 5, text: 'Εξαιρετικά αποτελέσματα θα τους σύστηνα ανεπιφύλακτα! Μου έλυσαν τα χέρια με την οργάνωση των ραντεβού μου, ενώ η πελατεία στο οδοντιατρείο μου στη Ρόδο άρχισε να αυξάνεται από τον πρώτο κιόλας μήνα της συνεργασία μας! Τα παιδιά με βοήθησαν άμεσα σε ό,τι τους ζητούσα και έχουν εξαιρετικά συστήματά και γνώσεις σε social media και ΑΙ.' },
      { image: DEFAULT_AVATAR + 'Βασιλική+Μπέλλου', name: 'Βασιλική Μπέλλου', rating: 5, text: 'Άριστοι επαγγελματίες. Άψογη συνεργασία. Μεταξωτη συμπεριφορά σε όλα τους. Ευγενεια, διαθεσιμότητα, χαμόγελο και ταχύτητα διεκπεραίωσης. Ειδικά ο Aggelos Metridis, μεταξωτος σε όλα του και κυρίως στον επαγγελματισμό του. Τους συστήνω ανεπιφύλακτα. Ευχαριστώ θερμά για την συνεργασία μας.' },
      { image: DEFAULT_AVATAR + 'Χριστίνα+Πανουσοπούλου', name: 'Χριστίνα Πανουσοπούλου', rating: 5, text: 'Εξαιρετική δουλειά! Έμεινα πολύ ευχαριστημένη με τη συνεργασία που είχαμε. Υπήρχε πάντα άμεση ανταπόκριση και με βοήθησαν σε ότι χρειάστηκα με διακριτικές αλλά εύστοχες προτάσεις. Συστήνεται ανεπιφύλακτα !' },
      { image: 'https://lh3.googleusercontent.com/a-/ALV-UjWET2TOFMS6lP_kbfwEgZsd4p_ptFmUSiCsQ66VwPYv6Gd8--Q=w144-h144-p-rp-mo-br100', name: 'Εμμανουέλα Ροκαδάκη', rating: 5, text: 'Άψογη δουλεία και συνεργασία. Με βοήθησαν πραγματικά σε ό,τι χρειάστηκα και υπήρχε πάντα άμεση ανταπόκριση. Ασύγκριτοι!' },
      { image: DEFAULT_AVATAR + 'Άσπα+Βούζα', name: 'Άσπα Βούζα', rating: 5, text: 'Παρά πολύ ευχαριστημένη με τη δουλειά των παιδιών. Άψογη συνεργασία και άμεση επικοινωνία Άσπα Βούζα - Οφθαλμιάτρος' },
      { image: DEFAULT_AVATAR + 'Θωμαή+Ζορμπά', name: 'Θωμαή Ζορμπά', rating: 5, text: 'Παρά πολύ καλή δουλειά και συνεργασία θα τους σύστηνα ανεπιφύλακτα - Θωμαη Ζορμπά Οδοντίατρος' },
      { image: DEFAULT_AVATAR + 'Ξένια+Παπαβραμίδου', name: 'Ξένια Παπαβραμίδου', rating: 5, text: 'Εξαιρετική δουλειά! Πολύ συνεπείς, με άμεσα αποτελέσματα.' },
      { image: DEFAULT_AVATAR + 'Ελένη+Αστρά', name: 'Ελένη Αστρά', rating: 5, text: 'Πολύ επαγγελματική δουλειά και άριστη συνεργασία - Ελένη Αστρά - Παιδίατρος' },
      { image: 'https://lh3.googleusercontent.com/a-/ALV-UjX9BSnfQVN3UY1kaqCVAO3J3YPFk6N_Ojtsr4chAJTQ1J96Clc=w144-h144-p-rp-mo-br100', name: 'Ιωάννης Λουκάς', rating: 5, text: 'Εξαιρετικοί επαγγελματίες και απόλυτα συνεπείς και καταρτισμένοι! Συστήνονται ανεπιφύλακτα.' },
      { image: DEFAULT_AVATAR + 'Μαρούσα+Σκυλάκη', name: 'Μαρούσα Σκυλάκη', rating: 5, text: 'ΑΨΟΓΗ ΔΟΥΛΕΙΑ ΚΑΙ ΣΥΝΕΡΓΑΣΙΑ ΜΕ ΑΜΕΣΗ ΕΠΙΚΟΙΝΩΝΙΑ. ΜΑΡΟΥΣΑ ΣΚΥΛΑΚΗ, ΔΕΡΜΑΤΟΛΟΓΟΣ.' },
      { image: DEFAULT_AVATAR + 'Φάνη+Φιλιπποπούλου', name: 'Φάνη Φιλιπποπούλου', rating: 5, text: '' },
      { image: DEFAULT_AVATAR + 'Στράτος+Χατζηστρατής', name: 'Στράτος Χατζηστρατής', rating: 5, text: '' },
    ],
    faqItems: [
      { question: 'Τι είναι η Advon Media;', answer: 'Είμαστε ένα ψηφιακό marketing agency που ειδικεύεται σε στρατηγική, social media και περιεχόμενο.' },
      { question: 'Ποιες υπηρεσίες προσφέρετε;', answer: 'Κατασκευή ιστοσελίδων, δημιουργία περιεχομένου + διαχείριση social media και ανέπαφες (NFC) βάσεις αξιολογήσεων.' },
      { question: 'Πόσο διαρκεί η παράδοση μιας ιστοσελίδας;', answer: 'Από τη στιγμή που έχουμε λάβει όλο το υλικό, μπορούμε να ολοκληρώσουμε την κατασκευή σε 5-10 ημέρες.' },
      { question: 'Πώς μπορώ να επικοινωνήσω;', answer: 'Στείλτε μας email στο advonmd@gmail.com και θα επικοινωνήσουμε άμεσα μαζί σας.' },
    ],
    servicesData: [
      {
        id: ServiceType.WEBSITE,
        icon: Globe,
        price: 'ΔΩΡΕΑΝ',
        priceNote: '(μόνο 10.83€/μήνα hosting)',
        title: 'Κατασκευή Ιστοσελίδας',
        shortDesc: 'Επαγγελματική ιστοσελίδα που κατακτά υψηλές θέσεις στη Google.',
        features: ['Επαγγελματικός σχεδιασμός', 'SEO βελτιστοποίηση', 'Mobile responsive', 'Παράδοση σε 5-10 ημέρες'],
        ctaText: 'Δωρεάν Κατασκευή',
        moreInfo: 'Περισσότερες πληροφορίες',
        modalContent: {
          title: 'Δωρεάν Κατασκευή Ιστοσελίδας',
          body: [
            'Δεν είναι κάποιο μάρκετινγκ τρικ, όντως η κατασκευή που κοστίζει κανονικά 700-2000€+, είναι εντελώς δωρεάν.',
            'Το μόνο κόστος για εσάς που δεν μπορούμε να καλύψουμε έιναι η φιλοξενία της ιστοσελίδας σε σέρβερ στο διαδίκτυο (γνωστό και ως hosting) και το domain name (το www.παράδειγμα.gr). Τα αναλαμβάνουμε και τα 2 σαν διαδικασίες εμείς!',
            'Το κάνουμε αυτό γιατί θέλουμε να προσθέσουμε όσες περισσότερες ιστοσελίδες γίνεται στο πορτφόλιο μας για να μπορούμε στο μέλλον και εμείς να έχουμε υψηλές τιμές και κέρδη.',
            'Συνολικά είναι μόνο 10.83€/μήνα (που θα πληρώνατε όπως και να έχει, όπου και αν κατασκευάζατε μια ιστοσελίδα, όπως πληρώνουν και όλοι που ήδη έχουν).',
            'Aναβαθμίστε την επαγγελματική σας παρουσία στο διαδίκτυο και μετατρέψτε τους επισκέπτες της ιστοσελίδας σας σε αφοσιωμένους πελάτες!',
            'Το 2025, η κατοχή μιας επαγγελματικής ιστοσελίδας δεν είναι απλώς ένα επιπλέον εργαλείο — είναι μια αναγκαιότητα για κάθε ελεύθερο επαγγελματία και επιχείρηση που θέλει να ξεχωρίσει στον ψηφιακό κόσμο.',
            'Μια καλά σχεδιασμένη ιστοσελίδα σας βοηθά να κατακτήσετε υψηλότερες θέσεις στις μηχανές αναζήτησης, καθώς η Google αξιολογεί τις ιστοσελίδες ως πιο αξιόπιστες και με πιο ολοκληρωμένο προφίλ.',
            'Η ιστοσελίδα σας λειτουργεί ως η ψηφιακή σας βιτρίνα, ενισχύοντας την επαγγελματική σας εικόνα και προβάλλοντας την επιχείρησή σας ως σοβαρή και αξιόπιστη στους επισκέπτες. Επιπλέον, προσφέρει στους χρήστες εύκολη πρόσβαση σε όλες τις απαραίτητες πληροφορίες, καθιστώντας την εμπειρία τους πιο άνετη και άμεση.',
            '----',
            'Πανεύκολη Διαδικασία Κατασκευής:',
            'Για να μειώσουμε τον χρόνο επένδυσης σας στην κατασκευή χρειαζόμαστε από εσάς μόνο:',
            '• 1) Τις φωτογραφίες που θέλετε να περιλαμβάνει η ιστοσελίδα σας (δική σας επαγγελματική, του χώρου ή/και του προσωπικού)',
            '• 2) Κάποια βασικά κείμενα για εσάς ή την επιχείρηση σας (μπορεί να είναι και πολύ μικρά, αναλμβάνουμε εμείς την κειμενογραφία)',
            '• 3) Τις υπηρεσίες σας μονολεκτικά',
            '• 4) Τα στοιχεία επικοινωνίας σας (τηλέφωνο, email, διεύθυνση, ωράριο λειτουργίας)',
            '• 5) Ένα λογότυπο αν έχετε, αλλιώς σας φτιάχνουμε ένα εμείς',
            'Όλα τα υπόλοιπα τα αναλαμβάνουμε εμείς (χρώματα design,κείμενα κλπ) και εννοείται μετά κάνουμε όσες αλλαγές επιθυμείτε.',
            'Εννοείται πως μπορείτε να μας στείλετε οτιδήποτε θα θέλατε να υπάρχει στην ιστοσελίδα σας. Τα παραπάνω είναι απλώς τα βασικά που χρειαζόμαστε και αρκούν για ένα εξαιρετικό και επαγγελματικό αποτέλεσμα.',
            'Διασφαλίστε ότι η επιχείρησή σας παραμένει μπροστά από τον ανταγωνισμό με μια ισχυρή, επαγγελματική παρουσία στο διαδίκτυο που κερδίζει την εμπιστοσύνη τόσο των επισκεπτών σας όσο και των μηχανών αναζήτησης.'
          ]
        }
      },
      {
        id: ServiceType.NFC,
        icon: Star,
        price: '25€',
        priceNote: 'εφάπαξ',
        title: 'Ανέπαφη Βάση Αξιολογήσεων',
        shortDesc: '50+ νέες αξιολογήσεις κάθε μήνα. Ανεβείτε στην κορυφή της Google σε 3 μήνες.',
        features: ['Αύξηση κριτικών Google', 'Βελτίωση τοπικού SEO', 'Εύκολη χρήση (NFC)', 'Χωρίς μηνιαία συνδρομή'],
        ctaText: 'Αγορά Τώρα',
        moreInfo: 'Περισσότερες πληροφορίες',
        modalContent: {
          title: 'Ανέπαφη Βάση Αξιολογήσεων',
          body: [
            'Ανεβείτε στη κορυφή της Google και αποκτήστε 150 νέες αξιολογήσεις σε λιγότερο απο 3 μήνες.',
            'Το πρώτο που κάνει κάποιος όταν αναζητεί μια επιχείρηση είναι να δει τις κριτικές της.',
            'Αν έχετε ελάχιστες είναι πολύ πιθανό να χάσετε πελάτες από τον ανταγωνισμό.',
            'Αλλά δεν είναι μόνο οι πελάτες που επηρεάζονται!',
            'Η Google, ως μηχανή αναζήτησης, θέλει να παρέχει τα πιο στοχευμένα αλλά και έγκυρα αποτελέσματα δίνοντας έτσι κύρια σημασία στις αξιολογήσεις.',
            'Όταν το ζητάτε από τους πελάτες σας συνήθως το ξεχνάνε ή δεν επενδύουν τον χρόνο να ψάξουν.',
            'Με την ανέπαφη βάση αξιολογήσεων μας μπορείτε να αποκτάτε τούλαχιστον 50 νέες κριτικές κάθε μήνα έυκολα και γρήγορα!',
            'Υπολογίστε και μόνοι σας (πχ 8 πελάτες ανά ημέρα, 20 εργάσιμες = 160 πελάτες τον μήνα. Αν λιγότεροι από τους μισόυς, οι 50, σας αφήσουν μια αξιολόγηση, έχετε 150 νέες σε 3 μήνες).'
          ]
        }
      },
      {
        id: ServiceType.SOCIAL,
        icon: Instagram,
        price: '87€/μήνα',
        title: 'Διαχείριση Social Media',
        shortDesc: 'Επαγγελματικά posts, hashtag research, copywriting. 7 ημέρες δωρεάν δοκιμή.',
        features: ['3 posts/εβδομάδα', 'Hashtag research', 'Copywriting', 'Μηνιαία αναφορά'],
        ctaText: 'Δωρεάν Δοκιμή',
        moreInfo: 'Περισσότερες πληροφορίες',
        modalContent: {
          title: 'ΕΠΑΓΓΕΛΜΑΤΙΚΗ ΔΙΑΧΕΙΡΙΣΗ SOCIAL MEDIA',
          body: [
            '• Επαγγελματικά Επεξεργασμένα Posts ανά ημέρα : Δημοσιεύουμε αναρτήσεις που τραβούν την προσοχή των πελατών σας, χρησιμοποιώντας προγράμματα επεξεργασίας συνδυαστικής αξίας 300+ευρώ τον μήνα, όπως Adscreative.io, Photoroom, Photoshop, Adobe Premium, Canvas Pro, Picsart Pro και άλλα.',
            '• Έρευνα Hashtags: Χρησιμοποιούμε τα καλύτερα hashtags ανάλογα με την επιχείρηση, τις υπηρεσίες, το κοινό και την τοποθεσία για να ενισχύσουμε την απήχησή σας και να σας φέρουμε μπροστά σε νέο κοινό.',
            '• Επαγγελματική Κειμενογραφία για κάθε ανάρτηση που οδηγούν τον αναγνώστη σε μια επιθυμητή ενέργεια (πχ να κλείσει ραντεβού κλπ)',
            '• Επεξεργασία - Δημιουργία επαγγελματικού βιογραφικού για το προφιλ σας',
            '• Αναφορές Προόδου: Παρέχουμε μηνιαία ανάλυση της ανάπτυξης των ακολούθων και της αλληλεπίδρασης με τις δημοσιεύσεις σας.',
            '• Ευκολία & Άνεση: Το μόνο που χρειάζεται να κάνετε είναι να μας στείλετε φωτογραφίες της επιχείρησής σας μέσω WeTransfer, και εμείς θα αναλάβουμε τα υπόλοιπα. Αν δεν έχετε μπορούμε να δημιουργούμε εμείς δικά μας designs, χωρίς καμία επένδυση χρόνου από εσάς!',
            'Δωρεάν Δοκιμή',
            'No contracts - cancel anytime',
            '----',
            'Γιατί να Μας Επιλέξετε:',
            'Οικονομικό πακέτο & Χωρίς Ρίσκο: Με μόνο 87 ευρώ τον μήνα και εγγύηση επιστροφής χρημάτων, αφαιρούμε κάθε ρίσκο από την απόφασή σας. Αν δεν είστε απόλυτα ικανοποιημένοι, σας επιστρέφουμε τα χρήματά σας – χωρίς ερωτήσεις.',
            'Προσωποποιημένη Υπηρεσία: Προσαρμόζουμε το περιεχόμενο σύμφωνα με τις ανάγκες της επιχείρησής σας, ώστε να αντανακλά την ταυτότητα και το στυλ σας.',
            'Άμεση Έναρξη: Κλείστε τη θέση σας τώρα – διαθέτουμε μόνο λίγες θέσεις για νέους πελάτες κάθε μήνα, ώστε να διατηρήσουμε την ποιότητα της υπηρεσίας μας.',
            'Καμία Δέσμευση: Μπορείτε να σταματήσετε οποιαδήποτε στιγμή χωρίς μακροχρόνια συμβόλαια.',
            'Αποτέλεσμα: Περισσότεροι Πελάτες & Επαγγελματική Παρουσία',
            'Με τη σωστή διαχείριση του Instagram, θα δείτε αυξημένη αλληλεπίδραση, μεγαλύτερη βάση πελατών, και ένα προφίλ που προσελκύει την προσοχή και δημιουργεί εμπιστοσύνη.',
            'Εγγραφείτε σήμερα και εξασφαλίστε την ειδική τιμή των 87€ μήνα.',
            'Στείλτε μας email στο advonmd@gmail.com για περαιτέρω επικοινωνία. (το ελέγχουμε καθημερινά)'
          ]
        }
      }
    ]
  },
  en: {
    nav: {
      services: 'Services',
      portfolio: 'Portfolio',
      reviews: 'Reviews',
      faq: 'FAQ',
      contact: 'Contact',
      lang: 'EL'
    },
    hero: {
      badge: 'ADVON MEDIA',
      titlePrefix: 'We Convert',
      titleHighlight1: 'Visitors',
      titleConnector: 'into',
      titleHighlight2: 'Customers',
      subtitle: 'The most effective marketing solutions for local businesses and freelancers. Rise to the top of results without risk.',
      ctaPrimary: 'SERVICES',
      ctaSecondary: 'PORTFOLIO'
    },
    stats: [
      { num: "2+", label: "YEARS OF EXPERIENCE" },
      { num: "50+", label: "HAPPY CLIENTS" },
      { num: "100%", label: "SUCCESS" },
      { num: "30+", label: "5-STAR REVIEWS" }
    ],
    sectionTitles: {
      services: 'Services',
      servicesMain: 'Solutions That Deliver',
      servicesSub: 'Complete solutions for your digital presence.',
      noCommitment: 'No commitment - Cancel Anytime',
      portfolio: 'Portfolio',
      portfolioMain: 'See Some of Our Work',
      portfolioSub: 'Work samples from satisfied clients.',
      viewSite: 'Visit Website',
      reviews: 'Reviews',
      reviewsMain: 'What Our Clients Say',
      viewAllReviews: 'See All Reviews',
      faq: 'Frequently Asked Questions',
      contact: 'Contact',
      contactMain: 'Let\'s Collaborate',
      contactSub: 'Send us an email with your phone number to discuss exactly what you need.'
    },
    portfolioItems: [
      { image: 'https://github.com/agelmet/Image-hosting-/blob/main/11.jpg?raw=true', url: 'https://talamagka-psychologos.gr/home', name: 'Talamagka Elpida - Psychologist' },
      { image: 'https://github.com/agelmet/Image-hosting-/blob/main/22.jpg?raw=true', url: 'https://roza-psychologist.gr', name: 'Roza Haroutiounian - Psychologist' },
      { image: 'https://github.com/agelmet/Image-hosting-/blob/main/33.jpg?raw=true', url: 'https://zampelis-psychology.gr', name: 'Zampelis Stefanos - Psychologist' },
      { image: 'https://github.com/agelmet/Image-hosting-/blob/main/44.jpg?raw=true', url: 'https://nakou-psychologos.gr', name: 'Nakou Dimitra - Psychologist' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/6720fff573cc5fde7d814b0c.png', url: 'https://rhodesdentist.gr', name: 'Glynos Georgios - Dentist' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/6720fff57002eeb8d74c581c.png', url: 'https://apartmentsin-greece.gr', name: 'Athens + Crete - Apartments' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/6720fff5be2f992fd50c4409.png', url: 'https://pediatrician-ioannisloukas.gr/en', name: 'Loukas Ioannis - Pediatrician' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/69025bdb3e45df05181238c1.jpeg', url: 'https://loulou-physiotherapy.gr', name: 'Loulou Chrysanthi - Physiotherapist' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/69025bdb7e579816e94176ed.jpeg', url: 'https://sofiavassiliadou-psyxiatros.gr', name: 'Vassiliadou Sofia - Psychiatrist' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/69025bdb5d191555856d1f45.jpeg', url: 'https://pappa-psyxologos.gr', name: 'Pappa Emmanuela - Psychologist' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/69025bdb10e4602f322522a4.jpeg', url: 'https://oikonomou-psyxologos.gr', name: 'Oikonomou Chrysoula - Psychologist' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/69025bdb5bfb334b18eec0a9.jpeg', url: 'https://stylianidou-psyxologos.gr', name: 'Stylianidou Sofia - Psychologist' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/69025bdbdf45434ecfb96d36.jpeg', url: 'https://tsekourakis-physiotherapy.gr', name: 'Tsekourakis Chronis - Physiotherapist' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/69031419ad87b047b548b858.jpeg', url: 'https://smaragdadimitra.gr', name: 'Dimitra Smaragda - Psychologist' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/690314195170a503ad1b3a49.jpeg', url: 'https://antamian-physiotherapy.gr', name: 'Antamian Ermioni - Physiotherapist' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/69031419ad87b0376a48b859.jpeg', url: 'https://dorasizopoulou.gr', name: 'Sizopoulou Theodora - Psychologist' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/690314195170a593181b3a4a.jpeg', url: 'https://zoetherapy.gr', name: 'Andreadaki Zoe - Psychologist' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/69031419762d2cf9e43378e1.jpeg', url: 'https://memagiagkini-psyxologos.gr', name: 'Giagkini Mema - Psychologist' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/68d954cfa1d2dc78adcfe610.jpeg', url: 'https://tsialiafa-dentalcare.gr', name: 'Tsialiafa Eleni - Dentist' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/68d954cfa1d2dc95f3cfe5fb.jpeg', url: 'https://chatzistratis-paidiatros.gr', name: 'Chatzistratis Stratos - Pediatrician' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/68d954cf4c35d613678773f5.jpeg', url: 'https://occludent.gr', name: 'Fasoula Maria - Dentist' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/68d954cfa1d2dc0857cfe5fc.jpeg', url: 'https://papathomas-vision.gr', name: 'Thomas Papathomas - Ophthalmologist' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/68d954cf337bbf261a42bbc3.jpeg', url: 'https://kk-dental.gr', name: 'Konstantinidis Konstantinos - Dentist' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/68d954cf4c35d6bcaf8773f6.jpeg', url: 'https://mysmile-prosthodontics.gr', name: 'Mordochai Nikitas - Dentist' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/6720fff5e811867d962b0b12.png', url: 'https://wonderfulspecs.gr', name: 'WonderfulSpecs - Opticals' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/6720fff57d6e345146f91a82.png', url: 'https://astra-paidiatros.gr', name: 'Astra Eleni - Pediatrician' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/672106acbe2f9908390c468b.png', url: 'https://barampouti-ofthalmiatros.gr', name: 'Barampouti Faye - Ophthalmologist' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/684c2972bc1bea3590d2fcd5.jpeg', url: 'https://eye-orl.gr', name: 'Ophthalmologist + ENT' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/684c2972e3c40936dec8067b.jpeg', url: 'https://davou-ofthalmiatros.gr', name: 'Davou Stavroula - Ophthalmologist' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/684c29725cb3bb547ceacc82.jpeg', url: 'https://vouza-ofthalmiatros.gr', name: 'Vouza Aspasia - Ophthalmologist' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/684c297207bcd3c2755ce584.jpeg', url: 'https://thetidasvilla.gr', name: 'Karpathos - Villa' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/684c297207bcd3a84a5ce586.jpeg', url: 'https://panousopoulou-paidiatros.gr', name: 'Panousopoulou Christina - Pediatrician' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/684c2972fbe6f42e908208cb.jpeg', url: 'https://giamouris-paidiatros.gr', name: 'Giamouris Manolis - Pediatrician' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/684c29722809a9b32a06926f.jpeg', url: 'https://theodosis-orila.gr', name: 'Theodosis Petros - ENT' },
      { image: 'https://assets.cdn.filesafe.space/61icdoMiJ2pHklO6mmKW/media/684c297251e5e5089ade7e7e.jpeg', url: 'https://zormpa-dentist.gr', name: 'Zormpa Thomais - Dentist' },
    ],
    reviews: [
      { image: 'https://lh3.googleusercontent.com/a-/ALV-UjXyvVDSorQzQz3Z-zsqvl68SOOgYiq4C3UBH8punVUaFZrC7wDkug=w144-h144-p-rp-mo-br100', name: 'Elpida Talamagka', rating: 5, text: 'I am a psychologist and collaborated with Advon Media for the creation of my professional site. The guys are excellent!!! Flawless work, 100% professionals & very consistent. Very polite & willing to discuss any change so that my site is exactly as I imagined it!! Aggelos thank you!!' },
      { image: DEFAULT_AVATAR + 'Roza+Haroutiounian', name: 'Roza Haroutiounian', rating: 5, text: 'My collaboration with the Advon Media team and especially with Mr. Aggelos for the creation of my professional profile was excellent. From the first moment he was polite, accessible and truly willing to listen to my wishes. He showed professionalism, consistency and interest in the best possible result, paying attention to detail and proposing very good ideas. I recommend them to anyone looking for quality work and excellent collaboration. Thank you very much! Roza Haroutiounian, Psychologist - Psychotherapist.' },
      { image: DEFAULT_AVATAR + 'Chrysa+Oikonomou', name: 'Chrysa Oikonomou', rating: 5, text: 'Excellent team! Our entire collaboration was flawless! From our first communication, their professionalism and experience were evident. They built my website with great speed, consistency and aesthetics. They were always available to answer my questions, propose solutions and immediately implement any modification I wanted to make. I recommend them unreservedly because the final result exceeded my expectations!' },
      { image: DEFAULT_AVATAR + 'Natalia+Grylonaki', name: 'Natalia Grylonaki', rating: 5, text: 'Excellent professionals. Polite and particularly willing from the beginning to solve all my questions and make any modification I desired. Consistent and creative. The final result, modern, functional and elegant, left me completely satisfied. I recommend them unreservedly.' },
      { image: 'https://lh3.googleusercontent.com/a-/ALV-UjXwzVoH8tFi5PJF8D8skvbm3K_MVRDQOVJDpeCoiW7ldSBbVCM=w144-h144-p-rp-mo-br100', name: 'Stylianidou Sofia', rating: 5, text: 'Excellent professionals, there was an immediate response in the creation of my website. Finally, they were open to explaining any question I had and changing anything needed. I recommend them unreservedly.' },
      { image: 'https://lh3.googleusercontent.com/a-/ALV-UjUIFeV7kJ81o_SxrHrpj0c_WK6-zPwV-xoJGSduKwsBrps_nN8=w144-h144-p-rp-mo-br100', name: 'Emmanuela Pappa', rating: 5, text: 'The guys were extremely professional, polite and willing to help at every stage of creating my site. They worked with incredible speed, listened carefully to what I wanted! The site came out exactly as I had imagined, simple, modern, functional and aesthetically flawless. I recommend them unreservedly!' },
      { image: DEFAULT_AVATAR + 'Maria+Fasoula', name: 'Maria Fasoula', rating: 5, text: 'Excellent professionals! Very reliable and consistent with schedules, with excellent communication and professional behavior. The website was delivered exactly as I imagined, functional and elegant. I highly recommend them for anyone looking for quality and responsible work!!!' },
      { image: DEFAULT_AVATAR + 'Eleni+Tsialiafa', name: 'Eleni Tsialiafa', rating: 5, text: 'Impeccable professionals with consistency and speed in service. Detailed and careful work. Bravo to the team! I recommend them unreservedly. Tsialiafa Eleni Surgeon Dentist' },
      { image: DEFAULT_AVATAR + 'Sofia+Vassiliadou', name: 'Sofia Vassiliadou', rating: 5, text: 'The entire Advon Media team operated with amazing professionalism and great speed. The result exceeded my expectations, I thank them very much and of course I recommend Advon Media unreservedly!' },
      { image: 'https://lh3.googleusercontent.com/a-/ALV-UjX1bbMbwmzkQEWSP45s29CBn4twUfVMISTrmfepCc8o3z9P8foekg=w144-h144-p-rp-mo-br100', name: 'Smaragda Dimitra', rating: 5, text: 'Excellent work, very good communication' },
      { image: 'https://lh3.googleusercontent.com/a-/ALV-UjVL1O97zqNUKHWBzFz9HIbvUc6__rUq_HdJELt-S-OZhixDk3fR=w144-h144-p-rp-mo-ba3-br100', name: 'Panagiotis Iatroudis', rating: 5, text: 'Very good and professional collaboration for the construction of my website. I have already recommended them to others! Iatroudis Panagiotis Dentist' },
      { image: 'https://lh3.googleusercontent.com/a-/ALV-UjWaGCVmAUJX0HX3Fxdt8YIs7h8Yn9py1LkLWI2h1lIqBvhgk89t=w144-h144-p-rp-mo-ba5-br100', name: 'Glynos Giorgos', rating: 5, text: 'Excellent results, I would recommend them unreservedly! They untied my hands with the organization of my appointments, while the clientele at my dental clinic in Rhodes started to increase from the very first month of our cooperation! The guys helped me immediately in whatever I asked for and have excellent systems and knowledge in social media and AI.' },
      { image: DEFAULT_AVATAR + 'Vasiliki+Bellou', name: 'Vasiliki Bellou', rating: 5, text: 'Excellent professionals. Flawless cooperation. Silky behavior in everything. Politeness, availability, smile and speed of processing. Especially Aggelos Metridis, silky in everything and mainly in his professionalism. I recommend them unreservedly. Thank you very much for our cooperation.' },
      { image: DEFAULT_AVATAR + 'Christina+Panousopoulou', name: 'Christina Panousopoulou', rating: 5, text: 'Excellent work! I was very satisfied with the cooperation we had. There was always an immediate response and they helped me with whatever I needed with discreet but accurate suggestions. Highly recommended!' },
      { image: 'https://lh3.googleusercontent.com/a-/ALV-UjWET2TOFMS6lP_kbfwEgZsd4p_ptFmUSiCsQ66VwPYv6Gd8--Q=w144-h144-p-rp-mo-br100', name: 'Emmanuela Rokadaki', rating: 5, text: 'Flawless work and cooperation. They really helped me in whatever I needed and there was always an immediate response. Incomparable!' },
      { image: DEFAULT_AVATAR + 'Aspa+Vouza', name: 'Aspa Vouza', rating: 5, text: 'Very happy with the guys\' work. Flawless cooperation and immediate communication Aspa Vouza - Ophthalmologist' },
      { image: DEFAULT_AVATAR + 'Thomais+Zormpa', name: 'Thomais Zormpa', rating: 5, text: 'Very good work and cooperation I would recommend them unreservedly - Thomais Zormpa Dentist' },
      { image: DEFAULT_AVATAR + 'Xenia+Papavramidou', name: 'Xenia Papavramidou', rating: 5, text: 'Excellent work! Very consistent, with immediate results.' },
      { image: DEFAULT_AVATAR + 'Eleni+Astra', name: 'Eleni Astra', rating: 5, text: 'Very professional work and excellent cooperation - Eleni Astra - Pediatrician' },
      { image: 'https://lh3.googleusercontent.com/a-/ALV-UjX9BSnfQVN3UY1kaqCVAO3J3YPFk6N_Ojtsr4chAJTQ1J96Clc=w144-h144-p-rp-mo-br100', name: 'Ioannis Loukas', rating: 5, text: 'Excellent professionals and absolutely consistent and qualified! Highly recommended.' },
      { image: DEFAULT_AVATAR + 'Marousa+Skylaki', name: 'Marousa Skylaki', rating: 5, text: 'FLAWLESS WORK AND COOPERATION WITH IMMEDIATE COMMUNICATION. MAROUSA SKYLAKI, DERMATOLOGIST.' },
      { image: DEFAULT_AVATAR + 'Fani+Filippopoulou', name: 'Fani Filippopoulou', rating: 5, text: '' },
      { image: DEFAULT_AVATAR + 'Stratos+Chatzistratis', name: 'Stratos Chatzistratis', rating: 5, text: '' },
    ],
    faqItems: [
      { question: 'What is Advon Media?', answer: 'We are a digital marketing agency specializing in strategy, social media, and content creation.' },
      { question: 'What services do you offer?', answer: 'Website construction, content creation + social media management, and contactless (NFC) review stands.' },
      { question: 'How long does website delivery take?', answer: 'From the moment we receive all the material, we can complete the construction in 5-10 days.' },
      { question: 'How can I contact you?', answer: 'Send us an email at advonmd@gmail.com and we will contact you immediately.' },
    ],
    servicesData: [
      {
        id: ServiceType.WEBSITE,
        icon: Globe,
        price: 'FREE',
        priceNote: '(only 10.83€/month hosting)',
        title: 'Website Construction',
        shortDesc: 'Professional website that conquers high rankings on Google.',
        features: ['Professional design', 'SEO optimization', 'Mobile responsive', 'Delivery in 5-10 days'],
        ctaText: 'Free Construction',
        moreInfo: 'More Information',
        modalContent: {
          title: 'Free Website Construction',
          body: [
            'It is not a marketing trick, indeed the construction that normally costs 700-2000€+, is completely free.',
            'The only cost for you that we cannot cover is the hosting of the website on a server on the internet (also known as hosting) and the domain name (www.example.gr). We undertake both as processes!',
            'We do this because we want to add as many websites as possible to our portfolio so that in the future we too can have high prices and profits.',
            'In total it is only 10.83€/month (which you would pay anyway, wherever you built a website, as everyone who already has one pays).',
            'Upgrade your professional presence on the internet and convert your website visitors into loyal customers!',
            'In 2025, owning a professional website is not just an extra tool — it is a necessity for every freelancer and business that wants to stand out in the digital world.',
            'A well-designed website helps you conquer higher positions in search engines, as Google evaluates websites as more reliable and with a more complete profile.',
            'Your website acts as your digital showcase, enhancing your professional image and projecting your business as serious and reliable to visitors. In addition, it offers users easy access to all necessary information, making their experience more comfortable and immediate.',
            '----',
            'Easiest Construction Process:',
            'To reduce your investment time in construction we need from you only:',
            '• 1) The photos you want your website to include (your own professional, of the space and/or staff)',
            '• 2) Some basic texts for you or your business (can be very small, we undertake the copywriting)',
            '• 3) Your services in one word',
            '• 4) Your contact details (phone, email, address, opening hours)',
            '• 5) A logo if you have one, otherwise we make one for you',
            'All the rest we undertake (colors design, texts etc) and of course then we make as many changes as you wish.',
            'Of course you can send us anything you would like to exist on your website. The above are just the basics we need and are enough for an excellent and professional result.',
            'Ensure that your business remains ahead of the competition with a strong, professional online presence that gains the trust of both your visitors and search engines.'
          ]
        }
      },
      {
        id: ServiceType.NFC,
        icon: Star,
        price: '25€',
        priceNote: 'one-off',
        title: 'Contactless Review Stand',
        shortDesc: '50+ new reviews every month. Rise to the top of Google in 3 months.',
        features: ['Increase Google reviews', 'Improve local SEO', 'Easy to use (NFC)', 'No monthly subscription'],
        ctaText: 'Buy Now',
        moreInfo: 'More Information',
        modalContent: {
          title: 'Contactless Review Stand',
          body: [
            'Rise to the top of Google and get 150 new reviews in less than 3 months.',
            'The first thing someone does when looking for a business is to see its reviews.',
            'If you have very few, it is very likely that you will lose customers to the competition.',
            'But it is not only customers who are affected!',
            'Google, as a search engine, wants to provide the most targeted but also valid results, thus giving main importance to reviews.',
            'When you ask your customers usually they forget or do not invest the time to search.',
            'With our contactless review base you can get at least 50 new reviews every month easily and quickly!',
            'Calculate for yourself (e.g. 8 customers per day, 20 working days = 160 customers per month. If less than half, 50, leave you a review, you have 150 new ones in 3 months).'
          ]
        }
      },
      {
        id: ServiceType.SOCIAL,
        icon: Instagram,
        price: '87€/month',
        title: 'Social Media Management',
        shortDesc: 'Professional posts, hashtag research, copywriting. 7 days free trial.',
        features: ['3 posts/week', 'Hashtag research', 'Copywriting', 'Monthly report'],
        ctaText: 'Free Trial',
        moreInfo: 'More Information',
        modalContent: {
          title: 'PROFESSIONAL SOCIAL MEDIA MANAGEMENT',
          body: [
            '• Professionally Edited Posts per day : We publish posts that grab your customers\' attention, using editing programs of combined value 300+euro per month, such as Adscreative.io, Photoroom, Photoshop, Adobe Premium, Canvas Pro, Picsart Pro and others.',
            '• Hashtag Research: We use the best hashtags depending on the business, services, audience and location to enhance your reach and bring you in front of a new audience.',
            '• Professional Copywriting for each post that leads the reader to a desired action (e.g. to book an appointment etc)',
            '• Editing - Creation of a professional biography for your profile',
            '• Progress Reports: We provide monthly analysis of follower growth and interaction with your posts.',
            '• Ease & Comfort: All you have to do is send us photos of your business via WeTransfer, and we will take care of the rest. If you don\'t have any we can create our own designs, without any time investment from you!',
            'Free Trial',
            'No contracts - cancel anytime',
            '----',
            'Why Choose Us:',
            'Economical package & Risk Free: With only 87 euros per month and a money back guarantee, we remove every risk from your decision. If you are not completely satisfied, we return your money – no questions asked.',
            'Personalized Service: We adapt the content according to your business needs, so that it reflects your identity and style.',
            'Immediate Start: Book your spot now – we have only a few spots for new customers every month, to maintain the quality of our service.',
            'No Commitment: You can stop at any time without long-term contracts.',
            'Result: More Customers & Professional Presence',
            'With the right Instagram management, you will see increased interaction, a larger customer base, and a profile that attracts attention and creates trust.',
            'Sign up today and secure the special price of 87€ month.',
            'Send us an email at advonmd@gmail.com for further communication. (we check it daily)'
          ]
        }
      }
    ]
  }
};
